name: SSH Test

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    env:
      MY_SSH_REMOTE_SERVER: 'admin@rabbeh.giize.com'  # modify as your remote server 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up SSH config
        run: |
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "${{env.MY_SSH_REMOTE_SERVER}}" 'echo "SSH connection successful"'
